### ISSUE TITLE
Discussions can't be replied to and commits were incorrect applied

### ISSUE THREAD

**Issue by OmgImAlexis** [thislooksfun/snoots#18]
Currently both discussions are locked to collaborators only.

The commits I made you also didn't apply instead you copied them so they're both now attributed to you even though I wrote the changes.

**Comment by thislooksfun** [comment]
> Currently both discussions are locked to collaborators only.

That is correct. As I have stated no less than 4 times now, [open a *new* discussion](https://github.com/thislooksfun/snoots/discussions/new?category=Ideas) and share what you're trying to do. 

> The commits I made you also didn't apply instead you copied them so they're both now attributed to you even though I wrote the changes.

I was unable to merge your PR because it contained multiple unrelated changes, only some of which I wanted to apply. I did credit you in each of those commits.

Additionally please do not use the issue tracker for non-bug-related reports. Discussions exist for a reason, please use them.
